### ISSUE TITLE
Duplicates functionality (and code) from alto-tools

### ISSUE THREAD

**Issue by mikegerber** [cneud/alto-ocr-text#1]
This duplicates the code/functionality from https://github.com/cneud/alto-tools.

**Comment by cneud** [comment]
Yeah this is the history: I initially wrote the various alto-* scripts but then decided to merge them into a single CLI. Unfortunately I had to stop halfway into the i/o implementation of [alto-tools](https://github.com/cneud/alto-tools), so left the simple scripts in place for users that needed sth working out of the box. Any fixes/PRs should thus better be made on the alto-tools repo and perhaps we can together fix the CLI (and move to ``click`` instead of ``argparse``).

**Comment by mikegerber** [comment]
AFAICS, we should fix cneud/alto-tools#2 and then alto-tools is ready to replace this (i.e. remove the script here and point to alto-tools in the README, at least that would be my suggestion).

**Comment by cneud** [comment]
> AFAICS, we should fix cneud/alto-tools#2 and then alto-tools is ready to replace this (i.e. remove the script here and point to alto-tools in the README, at least that would be my suggestion).

Yes, as soon as there is a working version of [alto-tools](https://github.com/cneud/alto-tools), the repos for the individual scripts will be archived.

**Comment by cneud** [comment]
(finally) done ;)
